back/api/urls.py
from django.urls import path
from .views import auth, games, user

app_name = 'api'

urlpatterns = [
   path('auth/sign-up', auth.sign_up),
   path('auth/sign-in', auth.sign_in),
   path('auth/sign-out', auth.sign_out),
   
   path('users/<str:username>', user.user),

   path('games', games.games),
   path('games/<str:slug>', games.game),
   path('games/<str:slug>/game_upload', games.game_upload),
   path('games/<str:slug>/last-version', games.game_version),
   
   path('games/<str:slug>/scores', games.scores),
   
]

back/panel/urls.py
from django.urls import path
from .views import auth, main

app_name = 'panel'

urlpatterns = [
   path('sign-in', auth.sign_up, name='sign-in'),
   path('', main.main, name='main'),   
   
   path('games/<int:game_id>', main.game_delete, name='game_delete'),      
]

back/settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('api/', include('api.urls')),
    path('panel/', include('panel.urls')),
]

back/panel/models.py
from django.db import models

# Create your models here.

back/panel/templates/panel/auth.html
{% include 'main.html' %}

{% block title %}
<title>Sign In</title>
{% endblock title %}

{% block content %}
<div class="home">
   <form action="" method="POST">
      {% csrf_token %}
      <h2>Login</h2>
      <input 
         type="text" 
         name="username" 
         placeholder="Enter your username..." >
         <input 
         type="password" 
         name="password" 
         placeholder="Enter your password..." >
         <button type="submit">Continue</button>
   </form>
</div>
{% endblock content %}

back/panel/templates/panel/home.html
{% include 'main.html' %}

{% block title %}
<title>Hi, {{request.user.username}}</title>
{% endblock title %}

{% block content %}
<div class="home__panel">
   <div class="home__panel__left">
      {% for game in games %}
         <div class="game">
            <h4>{{game.title}}</h4> 
            {{game.description}}
            <h4>{{game.author.username}}</h4>
            {{game.updated}}
            <h4>
               <a href="{% url 'panel:game_delete' game.id %}">delete</a>
            </h4>
         </div>
      {% endfor %}
   </div>
   <div class="home__panel__right">
      <h3>Admins</h3>
      {% for admin in admins %}
         <div class="admin">
            <h4>{{admin.username}}</h4> - {{admin.last_login}} - {{admin.date_joined}}
         </div>
      {% endfor %}
      <h3>Users</h3>
      {% for user in users %}
         <div class="admin game">
            <h4>{{user.username}}</h4>
            <a href="api/user/{{user.username}}">show</a>
            <form action="" name="isBlockedMessage" method="POST" class="block__form">
               <input type="hidden" name="isUserId" value="{{user.id}}" >
               <select name="block_message" id="">
                  <option disabled selected>Select Message</option>
                  <option value="You have been blocked by an administrator">You have been blocked by an administrator</option>
                  <option value="You have been blocked for spamming">You have been blocked for spamming</option>
                  <option value="You have been blocked for cheating">You have been blocked for cheating</option>
               </select>
               <input type="hidden" name="isBlocked" value="{{user.set_profile.isBlocked}}" >
               <button>Delete</button>
            </form>
         </div>
      {% endfor %}
   </div>
</div>
{% endblock content %}